@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(agent, "Оператор колл-центра")
Person(partnerAgent, "Оператор партнёрского колл-центра")

System_Boundary(callCenterSys, "Система колл-центра") {
 Container(callUi, "Интерфейс оператора", "React.js", "Показ ставок")
 Container(callApi, "API колл-центра", "Spring Boot", "Обработка данных")
}

System_Boundary(bankSite, "Сайт банка") {
 Container(rateModule, "Модуль ставок", "PHP/JS", "Хранит и предоставляет ставки")
}

System_Ext(partnerSystem, "Внешняя система колл-центра") {
 Container(fileReader, "Импорт файла", "CSV parser", "Чтение ставок из файла")
}

Rel(agent, callUi, "Просматривает ставки")
Rel(callUi, callApi, "Запрашивает данные")
Rel(callApi, rateModule, "Получает ставки", "REST/JSON")
Rel(rateModule, fileReader, "Экспортирует ставки", "CSV по расписанию")
Rel(partnerAgent, fileReader, "Читает ставки")
@enduml